export interface DiligenceQuestion {
  category: string;
  question: string;
  rationale: string;
}

export interface BusinessTermExplanation {
  term: string;
  definition: string;
  whyItMatters: string;
  exampleContext: string;
}

const COMMON_FINANCIAL_TERMS: Record<string, BusinessTermExplanation> = {
  arr: {
    term: "ARR (Annual Recurring Revenue)",
    definition: "The annualized value of predictable, recurring subscription revenue.",
    whyItMatters: "Helps assess stable, recurring demand versus one-time transactional sales.",
    exampleContext: "For SaaS companies, ARR is a standard metric of baseline contract health.",
  },
  cac: {
    term: "CAC (Customer Acquisition Cost)",
    definition: "Total sales and marketing expenditure divided by the number of customers acquired in a period.",
    whyItMatters: "Indicates how capital-efficient customer growth is.",
    exampleContext: "If CAC exceeds lifetime value (LTV), unit economics may not be sustainable long-term.",
  },
  ltv: {
    term: "LTV (Lifetime Value)",
    definition: "Estimated gross profit generated by an average customer over their relationship with the business.",
    whyItMatters: "When compared to CAC (ideally 3:1 or higher), indicates margin health and retention strength.",
    exampleContext: "High churn reduces LTV, requiring higher customer acquisition velocity.",
  },
  burn: {
    term: "Burn Rate & Runway",
    definition: "Burn rate is the monthly net cash outflow. Runway is total available cash divided by monthly net burn.",
    whyItMatters: "Shows how many months a startup can operate before requiring new financing or reaching cash-flow positivity.",
    exampleContext: "12–18 months of runway is standard minimum buffer during volatile capital markets.",
  },
  ebitda: {
    term: "EBITDA",
    definition: "Earnings Before Interest, Taxes, Depreciation, and Amortization.",
    whyItMatters: "Provides a proxy for operating cash profitability before capital structure and non-cash accounting adjustments.",
    exampleContext: "Often used in later-stage or manufacturing businesses to evaluate operational profitability.",
  },
  preseed: {
    term: "Pre-Seed & Seed Stage",
    definition: "Early company stages focused on validating product-market fit and initial customer traction.",
    whyItMatters: "Involves the highest operational and execution uncertainty, but potentially earliest entry valuation.",
    exampleContext: "Capital at this stage typically funds MVP engineering and initial go-to-market testing.",
  },
};

export function getTermExplanation(termQuery: string): BusinessTermExplanation | null {
  const normalized = termQuery.toLowerCase().replace(/[^a-z]/g, '');
  for (const [key, val] of Object.entries(COMMON_FINANCIAL_TERMS)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return val;
    }
  }
  return null;
}

export function getAllTerms(): BusinessTermExplanation[] {
  return Object.values(COMMON_FINANCIAL_TERMS);
}

export function generateDiligenceQuestions(business: {
  industry: string;
  businessStage: string;
  fundingRequirement: number;
  revenueStatus: string;
  profitabilityStatus: string;
}): DiligenceQuestion[] {
  const questions: DiligenceQuestion[] = [
    {
      category: "Unit Economics & Financial Sustainability",
      question: "What is your gross margin percentage and what are the main variable costs per customer or unit delivered?",
      rationale: "Evaluates whether growth generates incremental profit or scales operational losses.",
    },
    {
      category: "Capital Allocation & Milestone Plan",
      question: `Specifically how will the ₹${business.fundingRequirement.toLocaleString('en-IN')} funding requirement be allocated over the next 12-18 months?`,
      rationale: "Verifies whether the capital requested provides sufficient runway to reach the next tangible milestone.",
    },
    {
      category: "Customer Acquisition & Retention",
      question: "What is your primary acquisition channel, customer payback period, and net retention or repeat purchase rate?",
      rationale: "Assesses customer satisfaction and defensibility against competitor spending.",
    },
    {
      category: "Industry & Regulatory Landscape",
      question: `What regulatory licenses, data privacy standards, or sector-specific approvals govern your operations in ${business.industry}?`,
      rationale: "Identifies compliance bottlenecks or legal hurdles that could impede scaling.",
    },
    {
      category: "Execution & Competitive Defensibility",
      question: "What unique technical, distribution, or intellectual property advantage prevents a well-funded competitor from replicating your solution?",
      rationale: "Gauges long-term moats and product differentiation.",
    },
  ];

  if (business.revenueStatus.toLowerCase().includes('pre-revenue')) {
    questions.push({
      category: "Commercialization Timing",
      question: "What concrete steps remain before first paying customer conversion, and what pilot agreements are currently active?",
      rationale: "Critical for pre-revenue opportunities to estimate time-to-first-cash-receipt.",
    });
  }

  return questions;
}

export function generateFactualExecutiveSummary(business: {
  companyName: string;
  industry: string;
  businessStage: string;
  fundingRequirement: number;
  problem: string;
  solution: string;
  businessModel: string;
  revenueStatus: string;
  customerTraction?: string | null;
}): string[] {
  return [
    `Stage & Focus: Operates as an ${business.businessStage} business in the ${business.industry} sector.`,
    `Core Problem Addressed: ${business.problem.slice(0, 140)}${business.problem.length > 140 ? '...' : ''}`,
    `Value Proposition: ${business.solution.slice(0, 140)}${business.solution.length > 140 ? '...' : ''}`,
    `Commercial Model: ${business.businessModel.slice(0, 140)}${business.businessModel.length > 140 ? '...' : ''}`,
    `Financial Positioning: Current revenue posture reported as "${business.revenueStatus}", targeting ₹${business.fundingRequirement.toLocaleString('en-IN')} in funding for stated operational milestones.`,
    business.customerTraction
      ? `Reported Traction: ${business.customerTraction.slice(0, 140)}${business.customerTraction.length > 140 ? '...' : ''}`
      : `Reported Traction: Details submitted during diligence phase.`,
  ];
}

export const AI_DISCLAIMER_LABEL =
  "AI Research Assistant: This output synthesizes submitted facts and standard venture due diligence frameworks. It does NOT constitute financial advice, credit rating, investment recommendation, or profit projection.";
